/**
 * @author <a href="mailto:dozmaden@edu.hse.ru"> Deniz Ozmaden</a>
 */

package com.ozmaden;

import org.junit.jupiter.api.BeforeEach;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Тесты на класс Контакт
 */
class ContactTest {

    private Contact con;

    @BeforeEach
    void setUp() {
        con = new Contact("Ozmaden", "Denis", "-", "+79851275530",
                "-", "Mitino", "06.04.2002", "author");
    }

    @org.junit.jupiter.api.Test
    void getName() {
        assertEquals(con.getName(), "Denis");
    }

    @org.junit.jupiter.api.Test
    void getSurname() {
        assertEquals(con.getSurname(), "Ozmaden");
    }

    @org.junit.jupiter.api.Test
    void getPatronym() {
        assertEquals(con.getPatronym(), "-");
    }

    @org.junit.jupiter.api.Test
    void getMobilephone() {
        assertEquals(con.getMobilephone(), "+79851275530");
    }

    @org.junit.jupiter.api.Test
    void getHomephone() {
        assertEquals(con.getHomephone(), "-");
    }

    @org.junit.jupiter.api.Test
    void getAddress() {
        assertEquals(con.getAddress(), "Mitino");
    }

    @org.junit.jupiter.api.Test
    void getBirthday() {
        assertEquals(con.getBirthday(), "06.04.2002");
    }

    @org.junit.jupiter.api.Test
    void getAbout() {
        assertEquals(con.getAbout(), "author");
    }

    @org.junit.jupiter.api.Test
    void getId() {
        int id = 1; // this should be randomly generated by apache
        con = new Contact(id, "Ozmaden", "Denis", "-", "+79851275530",
                "-", "Mitino", "06.04.2002", "author");
        assertEquals(id, con.getId());
    }

    @org.junit.jupiter.api.Test
    void cutIfTooBig() {
        String str = "qwertyuiop[]asdfghjkl;'zxcvbnm,./";
        assertEquals(con.cutIfTooBig(str).length(), 18);
    }
}
